name: Generate Pac-Man Graph

on:
  schedule:
    - cron: "0 0 * * *"  # roda todos os dias à meia-noite UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Pacman Graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: marcovsilva

      - name: Upload to output branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output
          folder: . # Aqui está o segredo: os SVGs são salvos na raiz
          clean: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
